apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app
  labels:
    app: will-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: will-app
    spec:
      containers:
        - name: will-app
          image: wil42/playground:v1
          ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: will-app
spec:
  selector:
    app: will-app
  ports:
    - name : will-app
      protocol: TCP
      port: 8888
      targetPort: 8888
